# NumPy Tutorial

## Import Requirements

In [1]:
import numpy as np

### Ndarray Object

- A collection of items of the same type
- Zero-based indexing
- All elements in an ndarray must be the same dtype
- Create an ndarray using np.array()

In [2]:
# Example 1: 1D array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
# Example 2: 2D array
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

### Array Attributes

In [4]:
# Example 1: Shape of array
c = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array: \n{c}")
print("")
print(f"Shape: \n{c.shape}")

Array: 
[[1 2 3]
 [4 5 6]]

Shape: 
(2, 3)


In [5]:
# Example 2: Resize using .shape
c.shape = (3, 2)
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# Example 3: Reshape using .reshape
c = np.array([[1, 2, 3], [4, 5, 6]])
c.reshape(2, 3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Example 4: Create array using .arange
d = np.arange(24)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
# Example 5: Find number of dimensions using .ndim
d.ndim

1

In [9]:
# Example 6: Reshape the above array using .reshape
e = d.reshape(2, 4, 3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### Creating Arrays

In [10]:
# Example 1: Creating an uninitialized array with specified shape and dtype using .empty
f = np.empty([2, 3], dtype = float)
f  # It was given random values because we havent provided any values yet

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Example 2: Create an array of zeros with a specified size using .zeros
g = np.zeros([4, 4], dtype = int)
g

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
# Example 3: Create an array of ones with a specified size using .ones
h = np.ones([2, 2], dtype = int)
h

array([[1, 1],
       [1, 1]])

### Creating Arrays from Existing Data

- np.asarray and np.array are very similar
- np.asarray has fewer parameters and is best suited for converting exisitng Python sequences into ndarrays

In [13]:
# Example 1: Convert a list to an array using .asarray
i = [1, 2, 3]
j = np.asarray(i)
j

array([1, 2, 3])

In [14]:
# Example 2: Convert a list to an array with specific dtype using .asarray
i = [1, 2, 3]
k = np.asarray(i, dtype = float)
k

array([1., 2., 3.])

In [15]:
# Example 3: Convert a tuple to an array using .asarray
l = (1, 2, 3)
m = np.asarray(l)
m

array([1, 2, 3])

In [16]:
# Example 4: Convert a list of tuples to an array using .asarray
n = [(1, 2, 3), (4, 5, 6)]
o = np.asarray(n)
o

array([[1, 2, 3],
       [4, 5, 6]])

### Creating Arrays from Numerical Ranges

In [17]:
# Example 1: Create an array using .arange
p = np.arange(5)
p

array([0, 1, 2, 3, 4])

In [18]:
# Example 2: Create an array with specific dtype using .arange
q = np.arange(5, dtype = float)
q

array([0., 1., 2., 3., 4.])

In [19]:
# Example 3: Create an array with specific start point, stop point, and step size using .arange
r = np.arange(10, 20, 2)
r

array([10, 12, 14, 16, 18])

In [20]:
# Example 4: Create an array with a specified number of evenly spaced values using .linspace
s = np.linspace(10, 20, 5)  # This will create 5 values between 10 and 20 (inclusive) that are evenly spaced from each other
s

array([10. , 12.5, 15. , 17.5, 20. ])

In [21]:
# Example 5: Create an array with a specified number of evenly spaced values, not inclusive, using .linspace
t = np.linspace(10, 20, 5, endpoint = False)
t

array([10., 12., 14., 16., 18.])

In [22]:
# Example 6: Create an array with specified number of evenly spaced values and include the step size using .linspace
u = np.linspace(10, 20, 5, retstep = True)
u

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)

In [23]:
# Example 7: Create an array with evenly spaced values on a log scale using .logspace
v = np.logspace(1, 10, num = 10, base = 10)
v

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

### Indexing and Slicing

Returns a view of the data

There are 3 indexing methods available:
- Field access
- Basic slicing
- Advanced slicing

In [24]:
# Example 1: Slice an array using the slice function which contains start, stop, step parameters
w = np.arange(10)
x = slice(2, 7, 2)
w[x]

array([2, 4, 6])

In [25]:
# Example 2: Slice an array using indexing, the same concept of start, stop and step apply
w = np.arange(10)
w[2:7:2]

array([2, 4, 6])

In [26]:
# Example 3: Slice a single element from an array using indexing
w = np.arange(10)
w[5]

5

In [27]:
# Example 4: Slicing a multidimensional array using indexing
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
# Example 5: Slicing a multidimensional array more specifically using indexing
z = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Keep only the elements in the second column
print(z[..., 1])
print('\n')

# Keep only the elements in the second row
print(z[1, ...])
print('\n')

# Keep only the elements from the second column on
print(z[..., 1:])

[2 5 8]


[4 5 6]


[[2 3]
 [5 6]
 [8 9]]


### Advanced Indexing

Returns a copy of the data, keep in mind this will impact memory

In [29]:
# Example 1: Select specific values using advanced indexing
aa = np.array([[1, 2], [3, 4], [5, 6]])
print(aa)
y = aa[[0, 1, 2], [0, 1, 0]]  # This returns elements at the positions (0, 0), (1, 1), and (2, 0)
y

[[1 2]
 [3 4]
 [5 6]]


array([1, 4, 5])

In [30]:
# Example 2: Select the corner elements using advanced indexing
bb = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(bb)
print("")
print(bb.shape)
print("")

# Think in terms of the coordinates
# Rows first value and cols first value is position (0, 0), the top left value (0)
# Rows second value and cols second value is position (0, 2), the top right value (2)
# Rows third value and cols third value is position (3, 0), the bottom left value (9)
# Rows fourth value and cols third value is position (3, 2), the bottom right value (11)
rows = [[0, 0], [3, 3]]  # These "ordered pairs" (see above notes) can also be stored as arrays to increase speed
cols = [[0, 2], [0, 2]]
cc = bb[rows, cols]
cc

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

(4, 3)



array([[ 0,  2],
       [ 9, 11]])

In [31]:
# Example 3: Slicing multidimensional array versus advanced indexing
dd = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]])
# Slicing
ee = dd[1:4, 1:3]
print(ee)
print("")
# Advanced indexing
ff = dd[1:4, [1, 2]]
print(ff)

[[ 4  5]
 [ 7  8]
 [10 11]]

[[ 4  5]
 [ 7  8]
 [10 11]]


In [36]:
# Example 4: Boolean array indexing
gg = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(gg)

# Select all values greater than 5
hh = gg[gg > 5]
hh

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 6,  7,  8,  9, 10, 11])

In [39]:
# Example 5: Omit all NaNs from original array
ii = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(ii)
print("")
jj = ii[~np.isnan(ii)]
jj

[nan  1.  2. nan  3.  4.  5.]



array([1., 2., 3., 4., 5.])